#### MACHINE LEARNING
##### LAB 10
---
##### NUMPY BASICS
---

In [1]:
import numpy as np

**Create a numpy array of int, characters, float and find their shapes**

In [2]:
arr = np.arange(5, 10, dtype='int64')
print(arr, arr.shape)

[5 6 7 8 9] (5,)


In [3]:
arr = np.chararray((3, 3))
print(arr, arr.shape)

[['' '' '']
 ['' '' '']
 ['' '' b'\xfb']] (3, 3)


In [4]:
arr = np.arange(1, 10, dtype='float64')
print(arr, arr.shape)

[1. 2. 3. 4. 5. 6. 7. 8. 9.] (9,)


**Create a zeros, empty, identity , eye and a full array**

In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.empty((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.eye(3, M=4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [9]:
np.full((3, 3), 69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

**Declare an array having the datatype of object, is it possible?**

In [10]:
np.full(6, 4, dtype='object')

array([4, 4, 4, 4, 4, 4], dtype=object)

**Create an array having 5 equally spaced numbers ranging from 5 to 15**

In [11]:
np.linspace(5, 15, 5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

**Create a numpy array ranging from 1 to 100**

In [12]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

**Reshape the above array into (100,15). Is it possible?**

In [13]:
arr.reshape((100, 15)) # not possible

ValueError: cannot reshape array of size 100 into shape (100,15)

**Reshape the array into (100,10)**

In [14]:
arr.reshape((100, 10)) # not possible

ValueError: cannot reshape array of size 100 into shape (100,10)

**Flatten and ravel the reshaped array. What is the difference?**

In [15]:
arr = arr.reshape((50, -1))
arr

array([[  1,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [  9,  10],
       [ 11,  12],
       [ 13,  14],
       [ 15,  16],
       [ 17,  18],
       [ 19,  20],
       [ 21,  22],
       [ 23,  24],
       [ 25,  26],
       [ 27,  28],
       [ 29,  30],
       [ 31,  32],
       [ 33,  34],
       [ 35,  36],
       [ 37,  38],
       [ 39,  40],
       [ 41,  42],
       [ 43,  44],
       [ 45,  46],
       [ 47,  48],
       [ 49,  50],
       [ 51,  52],
       [ 53,  54],
       [ 55,  56],
       [ 57,  58],
       [ 59,  60],
       [ 61,  62],
       [ 63,  64],
       [ 65,  66],
       [ 67,  68],
       [ 69,  70],
       [ 71,  72],
       [ 73,  74],
       [ 75,  76],
       [ 77,  78],
       [ 79,  80],
       [ 81,  82],
       [ 83,  84],
       [ 85,  86],
       [ 87,  88],
       [ 89,  90],
       [ 91,  92],
       [ 93,  94],
       [ 95,  96],
       [ 97,  98],
       [ 99, 100]])

In [16]:
arr.flatten('F')

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99,   2,   4,
         6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,
        32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
        58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
        84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
arr.ravel('F')

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99,   2,   4,
         6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,
        32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
        58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
        84,  86,  88,  90,  92,  94,  96,  98, 100])

np.flatten and np.ravel works in exact same ways

**Take an array [[1 2 3] [4 5 6] [7 8 9]]. Sum it along 0 and 1 axis**

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.sum(axis=0), arr.sum(axis=1)

(array([12, 15, 18]), array([ 6, 15, 24]))

**Find the number of bytes used by your array**

In [19]:
arr.nbytes, arr.itemsize, arr.size

(72, 8, 9)

**Find the maximum and minimum values in a 1D array**

In [20]:
arr = np.arange(5, 15)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr.max()

14

**Find the maximum and minimum values in 2D array**

In [22]:
arr = arr.reshape((5, -1))
arr

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [23]:
arr.max()

14

**Sort an array**

In [24]:
arr = np.random.randint(0, 100, 5)
arr

array([45, 56, 48, 36, 20])

In [25]:
np.sort(arr)

array([20, 36, 45, 48, 56])

**Is \* and mul the same as dot product for numpy arrays and matrices? Check**

In [26]:
a = np.random.randint(0, 100, (3, 3))
b = np.random.randint(0, 100, (3, 3))

a, b

(array([[18, 49, 85],
        [16, 15, 64],
        [90, 39,  6]]),
 array([[71, 12, 10],
        [14, 23, 96],
        [12, 51, 74]]))

In [27]:
a*b

array([[1278,  588,  850],
       [ 224,  345, 6144],
       [1080, 1989,  444]])

In [28]:
np.multiply(a, b)

array([[1278,  588,  850],
       [ 224,  345, 6144],
       [1080, 1989,  444]])

In [29]:
np.dot(a, b)

array([[ 2984,  5678, 11174],
       [ 2114,  3801,  6336],
       [ 7008,  2283,  5088]])

np.dot is different from * and mul

**Take the square root and norm of an array**

In [30]:
a, np.sqrt(a)

(array([[18, 49, 85],
        [16, 15, 64],
        [90, 39,  6]]),
 array([[4.24264069, 7.        , 9.21954446],
        [4.        , 3.87298335, 8.        ],
        [9.48683298, 6.244998  , 2.44948974]]))

In [31]:
y = [[4, 4], 
     [3, 3]]

In [32]:
np.linalg.norm(y, axis=0)

array([5., 5.])

Eucledian Distance along axis

**Find the std, non-zero, zero values and mean of an array**

In [33]:
arr = np.random.randint(0, 10, 10)
arr

array([7, 0, 0, 1, 8, 3, 8, 2, 0, 5])

In [34]:
np.std(arr)

3.168595903550972

In [35]:
indexes = arr.nonzero()
indexes

(array([0, 3, 4, 5, 6, 7, 9]),)

In [36]:
arr[indexes]

array([7, 1, 8, 3, 8, 2, 5])

In [37]:
print(np.where(arr == 0), arr[np.where(arr == 0)])

(array([1, 2, 8]),) [0 0 0]


**Convert some angles to radians and vice versa**

In [38]:
import math

In [39]:
print(np.deg2rad([180, 360]), np.rad2deg([math.pi, 2*math.pi]))

[3.14159265 6.28318531] [180. 360.]


**Save and load some of your arrays**

In [40]:
arr

array([7, 0, 0, 1, 8, 3, 8, 2, 0, 5])

In [41]:
np.save('arr.npy', arr)

In [42]:
np.load('arr.npy')

array([7, 0, 0, 1, 8, 3, 8, 2, 0, 5])

**Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal**

In [43]:
arr = np.random.normal(21, 4.5, (3,3,12,3))
arr

array([[[[22.48504307, 20.37323129, 24.93548389],
         [ 9.41423231, 20.34988179, 18.13990954],
         [19.64113119, 27.17678949, 25.71322979],
         [18.09658761, 24.09963006, 14.1185587 ],
         [17.6653368 , 26.48952622, 20.17742685],
         [25.53290076, 32.2509569 , 24.68714777],
         [20.14445399, 22.73773867, 21.49663499],
         [20.07816208, 19.80020558, 20.37923595],
         [16.45164327, 21.24958901, 15.49368752],
         [20.94920605, 22.21894833, 16.65418654],
         [17.66353139, 23.75520271, 14.32452712],
         [26.90572269, 23.98575969, 23.54939005]],

        [[20.0874291 , 19.18852241, 23.11430066],
         [23.00117032, 23.35316649, 21.0256452 ],
         [17.84333031, 16.08184762, 24.59061328],
         [18.92443675, 22.1131451 , 19.60950785],
         [25.09084971, 25.59201462, 17.24249728],
         [25.40960167,  9.35756922, 27.14007287],
         [19.69667135, 19.27274436, 22.97424603],
         [17.32042315, 29.07150751, 22.31321115]

In [44]:
np.mean(arr, axis = 2)

array([[[19.5856626 , 23.70728831, 19.97245156],
        [21.14453089, 21.59503869, 21.74842627],
        [18.87861942, 20.29715991, 20.02679355]],

       [[21.97033137, 20.95236829, 21.09497401],
        [20.96802532, 21.95356391, 19.36233753],
        [23.10419487, 19.98367614, 20.73832944]],

       [[19.17569086, 19.41904492, 22.13113249],
        [19.74163245, 19.77099428, 21.18266685],
        [22.01853888, 22.13345383, 22.38528706]]])

In [45]:
np.std(arr, axis=2)

array([[[4.30751393, 3.41388356, 4.03874186],
        [3.53258963, 5.33195085, 2.61915868],
        [3.14332219, 3.53483542, 4.11155355]],

       [[2.64184907, 5.89430128, 5.34772426],
        [4.28289202, 4.4544381 , 2.99340671],
        [5.0423181 , 4.06403646, 5.27000998]],

       [[4.56483779, 4.24920555, 3.60885742],
        [4.74498917, 3.65479933, 4.66127396],
        [4.79626377, 6.77611962, 2.91319358]]])

In [46]:
np.var(arr, axis=2)

array([[[18.55467622, 11.65460098, 16.31143582],
        [12.47918953, 28.42969987,  6.85999218],
        [ 9.88047439, 12.49506147, 16.90487263]],

       [[ 6.9793665 , 34.74278756, 28.5981548 ],
        [18.34316409, 19.8420188 ,  8.96048374],
        [25.42497184, 16.51639235, 27.77300519]],

       [[20.83774408, 18.05574783, 13.02385188],
        [22.51492218, 13.35755811, 21.72747497],
        [23.00414618, 45.91579713,  8.48669681]]])

In [47]:
np.max(arr, axis=2)

array([[[26.90572269, 32.2509569 , 25.71322979],
        [29.11315485, 29.07150751, 27.14007287],
        [26.33152488, 26.21201531, 28.1576191 ]],

       [[26.42790465, 28.4807054 , 27.31386486],
        [29.58599403, 29.88015324, 22.74385372],
        [36.51579504, 25.45445104, 27.23013526]],

       [[27.6588273 , 28.19021597, 29.04456268],
        [26.52210667, 24.76485318, 30.41130693],
        [29.2420406 , 30.14455698, 27.70127018]]])

In [48]:
np.min(arr, axis=2)

array([[[ 9.41423231, 19.80020558, 14.1185587 ],
        [17.32042315,  9.35756922, 17.24249728],
        [16.06334453, 14.89588121, 11.71880777]],

       [[17.17487301,  6.11734418, 12.40985791],
        [15.09811238, 11.66386194, 13.51533325],
        [18.99345666, 12.6254553 , 10.45488477]],

       [[ 9.4629707 , 13.58650186, 14.73944656],
        [ 9.88517084, 13.71889739, 17.15111793],
        [14.82116569,  6.52463366, 16.96702922]]])